/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg9_jairosierra;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo Sierra
 */
public class Principal extends javax.swing.JFrame {
adminHackeos ap;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_super = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_riesgo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_supers = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jt_fallidos = new javax.swing.JTextField();
        jd_modsuper = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_codigo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_riesgo1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jd_regular = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_codigo2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_riesgo2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jt_fallidos1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_regular = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_modregular = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jt_codigo3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cb_riesgo3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jt_fallidos2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jd_simulacion = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_hackeos = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jt_caracteres = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        pg_t = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_crear = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_regular = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmi_simulacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setText("Hackeo Super");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Nivel de riesgo");

        cb_riesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", " " }));

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_supers.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_supers);

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Hackeos Fallidos");

        jt_fallidos.setEditable(false);
        jt_fallidos.setText("0");

        javax.swing.GroupLayout jd_superLayout = new javax.swing.GroupLayout(jd_super.getContentPane());
        jd_super.getContentPane().setLayout(jd_superLayout);
        jd_superLayout.setHorizontalGroup(
            jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_superLayout.createSequentialGroup()
                .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_superLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_superLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jd_superLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jd_superLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jt_fallidos))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_superLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_superLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addGap(32, 32, 32))
        );
        jd_superLayout.setVerticalGroup(
            jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_superLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_superLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jt_fallidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jd_superLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel5.setText("Hackeo Super");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Codigo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Nivel de riesgo");

        cb_riesgo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", " " }));

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modsuperLayout = new javax.swing.GroupLayout(jd_modsuper.getContentPane());
        jd_modsuper.getContentPane().setLayout(jd_modsuperLayout);
        jd_modsuperLayout.setHorizontalGroup(
            jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modsuperLayout.createSequentialGroup()
                .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modsuperLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton4))
                    .addGroup(jd_modsuperLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel5)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modsuperLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modsuperLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(29, 29, 29)
                            .addComponent(jt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modsuperLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cb_riesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
        jd_modsuperLayout.setVerticalGroup(
            jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modsuperLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(49, 49, 49))
            .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modsuperLayout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(jd_modsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cb_riesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel8.setText("Hackeo Regular");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Codigo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Nivel de riesgo");

        cb_riesgo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Hackeos Exitosos");

        jt_fallidos1.setEditable(false);
        jt_fallidos1.setText("0");

        jButton5.setText("Crear");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jl_regular.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_regular);

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_regularLayout = new javax.swing.GroupLayout(jd_regular.getContentPane());
        jd_regular.getContentPane().setLayout(jd_regularLayout);
        jd_regularLayout.setHorizontalGroup(
            jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_regularLayout.createSequentialGroup()
                .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_regularLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_regularLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(jd_regularLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addComponent(jt_codigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jd_regularLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jt_fallidos1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_regularLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_riesgo2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_regularLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addComponent(jButton6))))
                .addGap(32, 32, 32))
        );
        jd_regularLayout.setVerticalGroup(
            jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_regularLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_regularLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jt_codigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cb_riesgo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jt_fallidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(jd_regularLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel12.setText("Hackeo Regular");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Codigo");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Nivel de riesgo");

        cb_riesgo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("Hackeos Exitosos");

        jt_fallidos2.setEditable(false);
        jt_fallidos2.setText("0");

        jButton8.setText("Modificar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modregularLayout = new javax.swing.GroupLayout(jd_modregular.getContentPane());
        jd_modregular.getContentPane().setLayout(jd_modregularLayout);
        jd_modregularLayout.setHorizontalGroup(
            jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modregularLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jd_modregularLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(jt_fallidos2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modregularLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cb_riesgo3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_modregularLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jt_codigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_modregularLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton8)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jd_modregularLayout.setVerticalGroup(
            jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modregularLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(66, 66, 66)
                .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_codigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_riesgo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jd_modregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_fallidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton8))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel16.setText("Simulacion");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setText("Hackeos");

        jl_hackeos.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_hackeos);

        jLabel18.setText("Tiempo del hackeo");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Cantidad de caracteres");

        jButton9.setText("Avanzar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        pg_t.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel16))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jt_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel18)
                        .addGap(35, 35, 35)
                        .addComponent(pg_t, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButton9)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel17)))
                .addGap(19, 19, 19)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jt_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pg_t, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Hackeo Super");

        jmi_crear.setText("Crear");
        jmi_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_crear);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hackeo Regular");

        jmi_regular.setText("Crear");
        jmi_regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_regularActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_regular);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Admin Hackeos");

        jmi_simulacion.setText("Simulacion");
        jmi_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_simulacionActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_simulacion);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Archivo");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Cargar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String riesgo;
        String codigo;
        riesgo = cb_riesgo.getSelectedItem().toString();
        codigo = jt_codigo.getText();
        int numero = 1+i.nextInt(6);
        int fallidos=0;
        Super x = new Super(fallidos,codigo,riesgo);
        lista.add(x);
        DefaultListModel modelo = (DefaultListModel) jl_supers.getModel();
        modelo.clear();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i) instanceof Super){
                modelo.addElement(lista.get(i));
                jl_supers.setModel(modelo);
            }
            }
        JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        jt_codigo.setText("");
        cb_riesgo.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearActionPerformed
        // TODO add your handling code here:
        jd_super.setModal(true);
        jd_super.pack();
        jd_super.setLocationRelativeTo(this);
        jd_super.setVisible(true);
    }//GEN-LAST:event_jmi_crearActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(lista.get(jl_supers.getSelectedIndex()).getTipo().equals("")){
        String codigo = jt_codigo1.getText();
        String riesgo = cb_riesgo1.getSelectedItem().toString();
        lista.get(jl_supers.getSelectedIndex()).setCodigo(codigo);
        lista.get(jl_supers.getSelectedIndex()).setNivel(riesgo);
        DefaultListModel modelo = (DefaultListModel) jl_supers.getModel();
        modelo.clear();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i) instanceof Super){
                modelo.addElement(lista.get(i));
                jl_supers.setModel(modelo);
            }
            }
        JOptionPane.showMessageDialog(this, "Se modifico exitosamente");
        jt_codigo1.setText("");
        cb_riesgo1.setSelectedIndex(0);
        jd_modsuper.dispose();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jl_supers.getSelectedIndex() >= 0) {
            jt_codigo1.setText(((Super)lista.get(jl_supers.getSelectedIndex())).getCodigo());
            cb_riesgo.setSelectedItem(Integer.parseInt(((Super)lista.get(jl_supers.getSelectedIndex())).getNivel()));
            jd_modsuper.setModal(true);
        jd_modsuper.pack();
        jd_modsuper.setLocationRelativeTo(this);
        jd_modsuper.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un hackeo!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jl_supers.getSelectedIndex() >= 0) {
            lista.remove(jl_supers.getSelectedIndex());
            DefaultListModel modelo = (DefaultListModel) jl_supers.getModel();
        modelo.clear();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i) instanceof Super){
                modelo.addElement(lista.get(i));
                jl_supers.setModel(modelo);
            }
            }
        }else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un hackeo !");
        }
        JOptionPane.showMessageDialog(this, "Se elimino exitosamente");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String riesgo;
        String codigo;
        riesgo = cb_riesgo2.getSelectedItem().toString();
        codigo = jt_codigo2.getText();
        int numero = 1+i.nextInt(6);
        int fallidos=0;
        Regular x = new Regular(fallidos,codigo,riesgo);
        lista2.add(x);
        DefaultListModel modelo = (DefaultListModel) jl_regular.getModel();
        modelo.clear();
        for (int i = 0; i < lista2.size(); i++) {
            if(lista2.get(i) instanceof Regular){
                modelo.addElement(lista2.get(i));
                jl_regular.setModel(modelo);
            }
            }
        JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        jt_codigo2.setText("");
        cb_riesgo2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jl_regular.getSelectedIndex() >= 0) {
            jt_codigo3.setText(((Regular)lista2.get(jl_regular.getSelectedIndex())).getCodigo());
            cb_riesgo3.setSelectedItem(Integer.parseInt(((Regular)lista2.get(jl_regular.getSelectedIndex())).getNivel()));
            jd_modregular.setModal(true);
        jd_modregular.pack();
        jd_modregular.setLocationRelativeTo(this);
        jd_modregular.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un hackeo!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jl_regular.getSelectedIndex() >= 0) {
            lista2.remove(jl_regular.getSelectedIndex());
            DefaultListModel modelo = (DefaultListModel) jl_regular.getModel();
        modelo.clear();
        for (int i = 0; i < lista2.size(); i++) {
            if(lista2.get(i) instanceof Regular){
                modelo.addElement(lista2.get(i));
                jl_regular.setModel(modelo);
            }
            }
        }else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un hackeo !");
        }
        JOptionPane.showMessageDialog(this, "Se elimino exitosamente");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jmi_regularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_regularActionPerformed
        // TODO add your handling code here:
        jd_regular.setModal(true);
        jd_regular.pack();
        jd_regular.setLocationRelativeTo(this);
        jd_regular.setVisible(true);
    }//GEN-LAST:event_jmi_regularActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        if(lista2.get(jl_regular.getSelectedIndex()).getTipo().equals("")){
        String codigo = jt_codigo3.getText();
        String riesgo = cb_riesgo3.getSelectedItem().toString();
        lista2.get(jl_regular.getSelectedIndex()).setCodigo(codigo);
        lista2.get(jl_regular.getSelectedIndex()).setNivel(riesgo);
        DefaultListModel modelo = (DefaultListModel) jl_regular.getModel();
        modelo.clear();
        for (int i = 0; i < lista2.size(); i++) {
            if(lista2.get(i) instanceof Regular){
                modelo.addElement(lista2.get(i));
                jl_regular.setModel(modelo);
            }
            }
        JOptionPane.showMessageDialog(this, "Se modifico exitosamente");
        jt_codigo3.setText("");
        cb_riesgo3.setSelectedIndex(0);
        jd_modregular.dispose();
    }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jmi_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_simulacionActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_hackeos.getModel();
        modelo.clear();
        for (int i = 0; i < lista2.size(); i++) {
            modelo.addElement(lista2.get(i));
        }
        for (int j = 0; j < lista.size(); j++) {
            modelo.addElement(lista.get(j));
        }
        jl_hackeos.setModel(modelo);
        jd_simulacion.setModal(true);
        jd_simulacion.pack();
        jd_simulacion.setLocationRelativeTo(this);
        jd_simulacion.setVisible(true);
    }//GEN-LAST:event_jmi_simulacionActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String cadena = jt_caracteres.getText();
        int con=cadena.length();
        int numero1=0,numero2=0;
        numero1 = 1+i.nextInt(9);
        DefaultListModel modelo = (DefaultListModel) jl_hackeos.getModel();
        if (jl_hackeos.getSelectedIndex() >= 0) {
            if(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())) instanceof Regular){
                if(numero1 == Integer.parseInt(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())).getNivel())){
                    JOptionPane.showMessageDialog(this, "Se cancelo el hackeo");
                }
                else{
                    ((Regular)modelo.get(jl_hackeos.getSelectedIndex())).setTipo("Exitoso");
                    int f = ((Regular)modelo.get(jl_hackeos.getSelectedIndex())).getExitosos();
                    f++;
                    ((Regular)modelo.get(jl_hackeos.getSelectedIndex())).setExitosos(f);
                    int tem = Integer.parseInt(((Regular)modelo.get(jl_hackeos.getSelectedIndex())).getNivel());
                    HT = new adminTiempo(pg_t,con,((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())));
                    HT.setTem(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())));
                    HT.setNumero(con);
                    HT.start();
                    HT.setAvanzar(true);
                }
            }
            if(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())) instanceof Super){
                if(numero1 == Integer.parseInt(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())).getNivel())){
                    JOptionPane.showMessageDialog(this, "Se cancelo el hackeo");
                
                }else{
                    ((Super)modelo.get(jl_hackeos.getSelectedIndex())).setTipo("Fallido");
                    int f = ((Super)modelo.get(jl_hackeos.getSelectedIndex())).getFallidos();
                    f++;
                    ((Super)modelo.get(jl_hackeos.getSelectedIndex())).setFallidos(f);
                    HT = new adminTiempo(pg_t,con,((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())));
                    HT.setTem(((Hackeo)modelo.get(jl_hackeos.getSelectedIndex())));
                    HT.setNumero(con);
                    HT.start();
                    HT.setAvanzar(true);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un hackeo !");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        lista = new ArrayList();
        lista2 = new ArrayList();
        try{
            Hackeo tem;
            FileInputStream hola = new FileInputStream("./Archivos Binarios/Hackeo.cbm");
            ObjectInputStream obj = new ObjectInputStream(hola);
            try{
                while((tem = (Hackeo)obj.readObject())!=null){
                    if(tem instanceof Regular){
                        lista2.add(((Regular)tem));
                    }
                    if(tem instanceof Super){
                        lista.add(((Super)tem));
                    }
                }
                obj.close();
                hola.close();
            }catch(EOFException e){
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ap = new adminHackeos("./Archivos Binarios/Hackeo.cbm");
        ap.cargarArchivo();
        for (int j = 0; j < lista2.size(); j++) {
            ap.getLista().add(lista2.get(j));
        }
        for (int j = 0; j < lista.size(); j++) {
            ap.getLista().add(lista.get(j));
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_riesgo;
    private javax.swing.JComboBox<String> cb_riesgo1;
    private javax.swing.JComboBox<String> cb_riesgo2;
    private javax.swing.JComboBox<String> cb_riesgo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_modregular;
    private javax.swing.JDialog jd_modsuper;
    private javax.swing.JDialog jd_regular;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JDialog jd_super;
    private javax.swing.JList<String> jl_hackeos;
    private javax.swing.JList<String> jl_regular;
    private javax.swing.JList<String> jl_supers;
    private javax.swing.JMenuItem jmi_crear;
    private javax.swing.JMenuItem jmi_regular;
    private javax.swing.JMenuItem jmi_simulacion;
    private javax.swing.JTextField jt_caracteres;
    private javax.swing.JTextField jt_codigo;
    private javax.swing.JTextField jt_codigo1;
    private javax.swing.JTextField jt_codigo2;
    private javax.swing.JTextField jt_codigo3;
    private javax.swing.JTextField jt_fallidos;
    private javax.swing.JTextField jt_fallidos1;
    private javax.swing.JTextField jt_fallidos2;
    private javax.swing.JProgressBar pg_t;
    // End of variables declaration//GEN-END:variables
ArrayList<Super> lista = new ArrayList();
ArrayList<Regular> lista2 = new ArrayList();
Random i = new Random();
adminTiempo HT;
ArrayList<Hackeo> hola = new ArrayList();
}
